language: java
os:
  - linux
  - osx
matrix:
  exclude:
  - os: osx
    jdk: oraclejdk8
  - os: osx
    jdk: oraclejdk7
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
