language: java

os:
  - linux
  - osx
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk6
matrix:
  exclude:
  - os: osx
    jdk: oraclejdk8
  - os: osx
    jdk: oraclejdk7

# see http://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
